# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5574122ddf700f2bcf4215638adaa09fb54ca9803e6a046bed02102c8f4fffe94d6b0fdbc75e051418b9c58523702c789ad69568d39be3e2e158dcd521b8181c

test:
  secret_key_base: 68ed6f04592ac506e62efa3ae5eaa64b86a31f011e474c9070b91968db057d6e278b576b0feb73ec12973f495057ea11e6b42a92ee2be8b87a0e02b39c031adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
